import type { Metadata } from "next";
import { localeAlternates, absoluteUrl } from "./alternates";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000";
const SITE_NAME = "Hexa Terminal";

/**
 * Branded fallback social image, generated by app/opengraph-image.tsx
 * (1200x630 PNG). Absolute rather than relative so it never depends on
 * `metadataBase` resolution.
 */
export const DEFAULT_OG_IMAGE = `${SITE_URL}/opengraph-image`;

const DEFAULT_OG_ALT = "Hexa Terminal — software systems that run real businesses";

export type PageMetadataInput = {
  locale: string;
  /**
   * Locale-invariant path, e.g. `/services` or `/services/crm-platform`.
   * `""` is the home page. The locale prefix is added here.
   */
  path: string;
  title: string;
  description?: string | null;
  /** CMS `seo.canonical_url` override; defaults to this page's own URL. */
  canonical?: string | null;
  /** CMS `seo.og_image` / cover image; falls back to the branded default. */
  image?: string | null;
  ogType?: "website" | "article";
  robots?: Metadata["robots"];
  /** `article:published_time` -- only meaningful with `ogType: "article"`. */
  publishedTime?: string | null;
  /** `article:modified_time` -- only meaningful with `ogType: "article"`. */
  modifiedTime?: string | null;
};

/**
 * Builds the full per-page metadata block.
 *
 * Exists because Next merges `metadata` SHALLOWLY: a page that omits
 * `alternates` inherits the parent's object verbatim, and a page that sets
 * `openGraph` REPLACES the parent's wholesale rather than merging into it
 * (node_modules/next/dist/docs/01-app/03-api-reference/04-functions/generate-metadata.md).
 * Because the root layout's alternates describe the HOME page, every page that
 * returned only `{ title, description }` was declaring the home page as its own
 * canonical/hreflang target, and every page that set `openGraph` silently
 * dropped `og:url`, `og:site_name` and `og:locale`. Likewise `twitter` was set
 * only in the root layout, so every subpage advertised the home page's title
 * and description on social cards.
 *
 * So this helper always emits all of it explicitly. Use it for EVERY page --
 * partial metadata objects are what caused the drift.
 */
export function pageMetadata({
  locale,
  path,
  title,
  description,
  canonical,
  image,
  ogType = "website",
  robots,
  publishedTime,
  modifiedTime,
}: PageMetadataInput): Metadata {
  const url = absoluteUrl(locale, path);
  const desc = description ?? undefined;

  const images = [
    image
      ? { url: image }
      : { url: DEFAULT_OG_IMAGE, width: 1200, height: 630, alt: DEFAULT_OG_ALT },
  ];

  return {
    title,
    description: desc,
    alternates: {
      canonical: canonical || url,
      ...localeAlternates(path),
    },
    ...(robots !== undefined ? { robots } : {}),
    openGraph: {
      type: ogType,
      siteName: SITE_NAME,
      locale,
      url,
      title,
      description: desc,
      images,
      ...(ogType === "article"
        ? {
            publishedTime: publishedTime ?? undefined,
            modifiedTime: modifiedTime ?? undefined,
          }
        : {}),
    },
    twitter: {
      card: "summary_large_image",
      title,
      description: desc,
      images,
    },
  };
}
